### ISSUE TITLE
Clojurescript support?

### ISSUE THREAD

**Issue by pedroteixeira** [daviddpark/clj-json-patch#1]
Hi, is there any plans for releasing a clojurescript version of this library?
I'm actually interested of using with mori from plain javascript. Any suggestion?

cheers.

**Comment by ILoveHubGit** [comment]
Hi, I added it as a pull request. I know you had to wait a long time for this, but I think ClojureScript was not ready yet in 2014. I hope David will merge it soon so it can be used by everyone :-)

cheers

**Comment by daviddpark** [comment]
Thanks to @ILoveHubGit this is finally resolved with https://github.com/daviddpark/clj-json-patch/pull/13
