### ISSUE TITLE
unable to patch nested objects

### ISSUE THREAD

**Issue by taso42** [daviddpark/clj-json-patch#2]
Example:  

Consider these 2 objects:

```clojure
(def obj1 {"nested" {"foo" "bar"}})

(def obj2 {"nested" {"foo" "bar"
                     "zot" "baz"}})
```

`diff` works as expected:
```clojure
(diff obj1 obj2)
=> [{"value" "baz", "op" "add", "path" "/nested/zot"}]
```

But `patch` throws an exception:
```clojure
(patch obj1 (diff obj1 obj2))
Exception Unable to set value at '/nested/zot'. Consider adding a more explicit data structure as a child of an existing object.  clj-json-patch.util/add-patch-value (util.clj:131)
```

**Comment by daviddpark** [comment]
Great find, @taso42 Thanks for pointing this out to me. I will try to address this tomorrow.

**Comment by taso42** [comment]
@daviddpark I took at stab at this.  Please see PR #3 .  Seems to have fixed the problem.

**Comment by daviddpark** [comment]
@taso42 thanks for filing your issue and following up with a pull request. If you are happy with the current state, I'll let you accept and close this issue.

**Comment by taso42** [comment]
thanks for merging it!
