### ISSUE TITLE
Adding to object within an array duplicates the array element

### ISSUE THREAD

**Issue by taso42** [daviddpark/clj-json-patch#6]
This is similar to #4 

```clojure
(def obj {"array" [{"id" "hello"}]})

(def ops [{"op" "add" "path" "/array/0/foo" "value" "bar"}])

(patch/patch obj ops)

```

actual:
```clojure
=> {"array" [{"id" "hello", "foo" "bar"} {"id" "hello"}]}
```

expected:
```clojure
=> {"array" [{"id" "hello", "foo" "bar"}]}
```

**Comment by daviddpark** [comment]
Feel free to submit a patch, but an interim solution could be to `[{"op" "replace" "path" "/array/0" "value" (assoc {"id" "hello"} "foo" "bar")]`

Otherwise, I will try to address this at some point this weekend.
